# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dataframe_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64\x61taframe_service.proto\x12\tdataframe\"3\n\x10\x44\x61taFrameRequest\x12\x0f\n\x07\x66\x65\x65\x64_id\x18\x01 \x01(\t\x12\x0e\n\x06job_id\x18\x02 \x01(\t\"2\n\x11\x44\x61taFrameResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"@\n\x0f\x44\x61taFrameUpdate\x12\x0f\n\x07\x66\x65\x65\x64_id\x18\x01 \x01(\t\x12\x0e\n\x06job_id\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x32\xb0\x01\n\x10\x44\x61taFrameService\x12P\n\x13GetInitialDataFrame\x12\x1b.dataframe.DataFrameRequest\x1a\x1c.dataframe.DataFrameResponse\x12J\n\rStreamUpdates\x12\x1b.dataframe.DataFrameRequest\x1a\x1a.dataframe.DataFrameUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dataframe_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATAFRAMEREQUEST']._serialized_start=38
  _globals['_DATAFRAMEREQUEST']._serialized_end=89
  _globals['_DATAFRAMERESPONSE']._serialized_start=91
  _globals['_DATAFRAMERESPONSE']._serialized_end=141
  _globals['_DATAFRAMEUPDATE']._serialized_start=143
  _globals['_DATAFRAMEUPDATE']._serialized_end=207
  _globals['_DATAFRAMESERVICE']._serialized_start=210
  _globals['_DATAFRAMESERVICE']._serialized_end=386
# @@protoc_insertion_point(module_scope)
