# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dataframe_service_pb2 as dataframe__service__pb2

GRPC_GENERATED_VERSION = '1.65.5'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dataframe_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class DataFrameServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInitialDataFrame = channel.unary_unary(
                '/dataframe.DataFrameService/GetInitialDataFrame',
                request_serializer=dataframe__service__pb2.DataFrameRequest.SerializeToString,
                response_deserializer=dataframe__service__pb2.DataFrameResponse.FromString,
                _registered_method=True)
        self.StreamUpdates = channel.unary_stream(
                '/dataframe.DataFrameService/StreamUpdates',
                request_serializer=dataframe__service__pb2.DataFrameRequest.SerializeToString,
                response_deserializer=dataframe__service__pb2.DataFrameUpdate.FromString,
                _registered_method=True)


class DataFrameServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInitialDataFrame(self, request, context):
        """Fetch initial large DataFrame
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamUpdates(self, request, context):
        """Stream updates in mini-batches or single rows
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataFrameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInitialDataFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInitialDataFrame,
                    request_deserializer=dataframe__service__pb2.DataFrameRequest.FromString,
                    response_serializer=dataframe__service__pb2.DataFrameResponse.SerializeToString,
            ),
            'StreamUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamUpdates,
                    request_deserializer=dataframe__service__pb2.DataFrameRequest.FromString,
                    response_serializer=dataframe__service__pb2.DataFrameUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataframe.DataFrameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dataframe.DataFrameService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataFrameService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInitialDataFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataframe.DataFrameService/GetInitialDataFrame',
            dataframe__service__pb2.DataFrameRequest.SerializeToString,
            dataframe__service__pb2.DataFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dataframe.DataFrameService/StreamUpdates',
            dataframe__service__pb2.DataFrameRequest.SerializeToString,
            dataframe__service__pb2.DataFrameUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
